apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-volume-claim
  namespace: frigate-server
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "1Gi"
