#example deployment and post customsiation for Photon VM
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: tinywin.ova
  namespace: default
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
spec:
  className: guaranteed-small
  imageName: 192.168.0.10:9000/tinywin.ova
  powerState: poweredOn
  networkInterfaces:
  - networkName: "VM Network"
    ethernetCardType: "vmxnet3"
  vmMetadata:
    configMapName: user-data-windows
    transport: CloudInit
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: user-data-windows
    namespace: default
data:
  user-data: |
    #ps1
    Install-WindowsFeature -Name Print-Server
    Restart-Computer