#example deployment and post customsiation for Photon VM
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: photon-vm
  namespace: default
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
spec:
  className: guaranteed-small
  #please don't include http/https prefix in the address. 
  #We will detect it automatically and also to make it compatible with container image naming spec)
  imageName: packages.vmware.com/photon/4.0/GA/ova/photon-hw11-4.0-1526e30ba0.ova
  powerState: poweredOn
  networkInterfaces:
  - networkName: "VM Network"
    ethernetCardType: "vmxnet3"
  vmMetadata:
    configMapName: user-data-photon
    transport: CloudInit
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: user-data-photon
    namespace: default
data:
  user-data: |
    #cloud-config
    ssh_pwauth: true
    users:
      - name: root
        sudo: ALL=(ALL) NOPASSWD:ALL
        lock_passwd: false
        passwd: '$6$eXrmWR89BbcQ.$3kKTW6Jeu63H8dj3vKWJGI8tV09jk5hc0vDBxNvSqlwZaFYMvNbJoZsAbTAW6HxWRot7bAWAWDayZezmWu8fn0.'
        shell: /bin/bash
    write_files:
      - content: |
          Keswick VM service says Hello World
        path: /helloworld